### ISSUE TITLE
Bug: Skill tracker doesn't include 4 free language points for Cultural Origin

### ISSUE THREAD

**Issue by TekDragon** [ray-cw/roll20-CPR-charactersheet#2]
Page 90: Don't forget the 4 Levels of Language you get free based on the Cultural Origin section of your Lifepath
(see pg. 45).

**Comment by ray-cw** [comment]
I do remember that, perhaps I could rename one of the skills as 'Cultural Language' and the base is always fixed to 4, to prevent players from moving the skillpoints elsewhere

**Comment by TekDragon** [comment]
That sounds like a good solution. 

Also, thanks for being so responsive. Our group really appreciates the work you've done with this.

**Comment by ray-cw** [comment]
Of course! I wouldn't be doing all this if I wasn't at least enjoying (and desperately need it for my own campaign)

**Comment by ray-cw** [comment]
To close the issue:
- Base skill points total increased to 90
- Added reset skills button (under settings) that automatically distributes mandatory 2 points across all basic skills + 4 to cultural
