### ISSUE TITLE
Enhancement: Need an additional column for skills or some other functionality for skill-boosting bonuses

### ISSUE THREAD

**Issue by TekDragon** [ray-cw/roll20-CPR-charactersheet#4]
An extra column would give players a place to add points from gear like Techscanners and Medscanners, plus other story-related bonuses a DM might give. 

This is important because you don't want to add those points to the base skill level, because base skill level is what you use to track the cost of improving skills. So you need to keep bonuses separate.

**Comment by ray-cw** [comment]
Just pushed the fix, please checkout the updated HTML and CSS files

**Comment by TekDragon** [comment]
Works great, thanks!
